name: firstWorkflow

on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
